# Generated by Django 4.2.1 on 2023-06-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs_num', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('is_healthy', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inverter', 'inverter'), ('and', 'and'), ('or', 'or'), ('nand', 'nand'), ('nor', 'nor'), ('xor', 'xor'), ('buffer', 'buffer')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('gates', models.ManyToManyField(related_name='system', to='circuits_parser.gate')),
                ('inputs', models.ManyToManyField(related_name='system_input', to='circuits_parser.io')),
                ('outputs', models.ManyToManyField(related_name='system_output', to='circuits_parser.io')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_name', models.CharField(max_length=20)),
                ('inputs', models.ManyToManyField(related_name='observation_input', to='circuits_parser.io')),
                ('outputs', models.ManyToManyField(related_name='observation_output', to='circuits_parser.io')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='circuits_parser.system')),
            ],
        ),
        migrations.AddField(
            model_name='gate',
            name='inputs',
            field=models.ManyToManyField(related_name='input_gate', to='circuits_parser.io'),
        ),
        migrations.AddField(
            model_name='gate',
            name='logical_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits_parser.component'),
        ),
        migrations.AddField(
            model_name='gate',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_gate', to='circuits_parser.io'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_gates', models.ManyToManyField(to='circuits_parser.gate')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='circuits_parser.observation')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='operator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits_parser.operatortype'),
        ),
    ]
