# Generated by Django 4.2.1 on 2023-07-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits_parser', '0003_parse_systems_and_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncertainObservation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('circuits_parser.observation',),
        ),
    ]
